// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD6e_y6FEDJ8q5HfbAK59PEBPYhUOArQLY',
    appId: '1:828358944958:web:9e208d093340ca4e5856ef',
    messagingSenderId: '828358944958',
    projectId: 'intranet-movil',
    authDomain: 'intranet-movil.firebaseapp.com',
    storageBucket: 'intranet-movil.appspot.com',
    measurementId: 'G-SDRC8R4D45',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBxU2nuK7Ti4jQ3SJ3-dpQHnc0RixkxGm8',
    appId: '1:828358944958:android:b487ae39994c1e2f5856ef',
    messagingSenderId: '828358944958',
    projectId: 'intranet-movil',
    storageBucket: 'intranet-movil.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC-L2UZ5ozaiVqOmkCipRUET3GOX1M7DZM',
    appId: '1:828358944958:ios:d798d38ddf9085625856ef',
    messagingSenderId: '828358944958',
    projectId: 'intranet-movil',
    storageBucket: 'intranet-movil.appspot.com',
    iosClientId: '828358944958-3ssv2aihj6f89itiu5n1cdn17be8vtkm.apps.googleusercontent.com',
    iosBundleId: 'com.promolife.intranet-movil-unlisted',
  );
}
